name: Build and Generate GIF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-generate-gif:
    runs-on: windows-latest

    steps:
    # 1. Pobierz kod z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Skonfiguruj .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    # 3. Zainstaluj zależności NuGet
    - name: Restore dependencies
      run: dotnet restore GraffitiAnimation/GraffitiAnimation.csproj

    # 4. Skompiluj projekt
    - name: Build project
      run: dotnet build GraffitiAnimation/GraffitiAnimation.csproj --configuration Release --no-restore

    # 5. Uruchom aplikację i wygeneruj GIF
    - name: Run application and generate GIF
      run: dotnet run --project GraffitiAnimation/GraffitiAnimation.csproj --configuration Release
      env:
        DISPLAY: ':0' # Wymagane dla headless rendering na Windows (jeśli potrzebne)

    # 6. Prześlij wygenerowany GIF jako artefakt
    - name: Upload GIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-gif
        path: GraffitiAnimation/bin/Release/net6.0-windows/output.gif
        if-no-files-found: warn