name: Build and Generate GIF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-generate-gif:
    runs-on: windows-latest

    steps:
    # 1. Pobierz kod z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Skonfiguruj .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    # 3. Zainstaluj zależności NuGet
    - name: Restore dependencies
      run: dotnet restore GraffitiAnimation.csproj

    # 4. Skompiluj projekt
    - name: Build project
      run: dotnet build GraffitiAnimation.csproj --configuration Release --no-restore

    # 5. Uruchom aplikację i wygeneruj GIF
    - name: Run application and generate GIF
      run: dotnet run --project GraffitiAnimation.csproj --configuration Release
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true # Może pomóc w problemach z renderowaniem

    # 6. Sprawdź, czy GIF został wygenerowany
    - name: Check GIF existence
      run: |
        if (-not (Test-Path bin/Release/net6.0-windows/output.gif)) {
          Write-Error "GIF file not found!"
          exit 1
        }

    # 7. Prześlij wygenerowany GIF jako artefakt
    - name: Upload GIF artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-gif
        path: bin/Release/net6.0-windows/output.gif
        if-no-files-found: error